services:
  postgres:
    image: 'postgres:15'
    environment:
      - 'POSTGRES_DB=db_payment_service'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=user'
    ports:
      - '5436:5432'
